name: blinQ Sync with upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # Runs at 02:00 every night

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Configure git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git config pull.rebase true

    - name: Add upstream remote
      run: git remote add upstream https://github.com/aztfmod/rover.git

    - name: Fetch changes from upstream main branch
      run: |
        git fetch upstream main
        git checkout main
        git merge upstream/main

    - name: Push changes to main branch
      run: git push origin main
